on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main, develop ]
    paths-ignore:
      - 'azure_pipelines/azure-pipelines.yml'
      - '.github/workflows/github-azure-repos.yml'

permissions:
  id-token: write
  contents: read

jobs:
  compare:
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}  # ← PRの発行元ブランチ
          fetch-depth: 0

      - name: Fetch to Azure Repos
        run: |
          echo "head_ref=${{ github.head_ref }}"
          echo "ref_name=${{ github.ref_name }}"

          git remote add azure https://ai-constr-vision:$AZURE_PAT@dev.azure.com/ai-constr-vision/static-web-apps/_git/github-azure-repos
          git fetch azure
          
        env:
          AZURE_PAT: ${{ secrets.AZURE_DEVOPS_EXT_PAT }}

#git --no-pager diff azure/{{ github.head_ref }}..HEAD
#git diff --stat azure/${{ github.head_ref }}..HEAD
  # sync:
  #   if: ${{ github.event_name == 'push' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Push to Azure Repos
  #       run: |
  #         git remote add azure   https://ai-constr-vision:$AZURE_PAT@dev.azure.com/ai-constr-vision/static-web-apps/_git/github-azure-repos
  #         git config user.name "GitHub Sync Bot"
  #         git config user.email "bot@github.com"
  #         git fetch azure ${{ github.ref_name }}
  #         git push azure  ${{ github.ref_name }} --force-with-lease
  #       env:
  #         AZURE_PAT: ${{ secrets.AZURE_DEVOPS_EXT_PAT }}

